### PR TITLE
improv. fix IllegalArgumentException

### PR DESCRIPTION
**Pull request by nivcoo**
Hello, i've fixed this error : https://hastebin.com/hikujadera.properties (For wildstacker spawner with crowbar for example).

### CODE REVIEW

**Comment by OmerBenGera** [comment]
Please re-upload the error, as from your fix you only add try-catch to the error.
There might be a better solution for that, but I can't know it without the error itself.

**Comment by nivcoo** [comment]
OH sorry the hastebin failed, https://pastebin.com/1Z62KqUt

**Comment by nivcoo** [comment]
I don't find the way to check if material has statistic or not so i've try catch

**Comment by OmerBenGera** [comment]
I think Player#getStatistic can return null, and if it's null, then it's not a validate statistic.
Try it instead of try-catch on that exception.

**Comment by nivcoo** [comment]
I will try

**Comment by nivcoo** [comment]
Nots works, the Player#getStatistic has also the IllegalArgumentException

**Comment by nivcoo** [comment]
https://pics.revolis.fr/2021-08/24/16-20_nQdT.png

**Comment by OmerBenGera** [comment]
right, my bad - there's no easy way to check for that. Merged.

**Pull request merged**
